# Docker file that installs docker container for Selenzyme
#
# build with: "sudo docker build -t selenzyme ."    anaconda3:5.0.1
FROM continuumio/anaconda3:5.2.0

 # Installtool: emboss=5.5.7s
RUN conda install -c conda-forge flask-restful=0.3.6 --no-update-dependencies \
  && conda install -c bioconda emboss=6.5.7 \
  && conda install -c rdkit rdkit=2017.09.3.0 \
  && conda install -c anaconda biopython=1.69 \
  && conda install -c biobuilds t-coffee=11.00
